name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.15
      uses: actions/setup-go@v2
      with:
        go-version: ^1.15
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Build
      run: go build -v .
      
    - name: Test
      run: go test -v .
      
    - name: Lint
      uses: Jerome1337/golint-action@v1.0.2
      with:
        golint-path: ./
    
    - name: Go report card
      # You may pin to the exact commit or the version.
      # uses: creekorful/goreportcard-action@1f35ced8cdac2cba28c9a2f2288a16aacfd507f9
      uses: creekorful/goreportcard-action@v1.0

